// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isStorageUsable } from '@/lib/auth-storage';

const SUPABASE_URL = "https://zhtfygjxnyxqsmeoipst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodGZ5Z2p4bnl4cXNtZW9pcHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTc3OTgsImV4cCI6MjA2OTQzMzc5OH0.e6BfsKvqmRYiRLO4DLqvylmV7smrlmVKBmKjRq2i5zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Storage selection: prefer localStorage, fall back to sessionStorage, then
// to an in-memory Map (iOS private mode blocks both real storages).
const createMemoryStorage = (): Storage => {
  const m = new Map<string, string>();
  return {
    getItem: (k) => m.get(k) ?? null,
    setItem: (k, v) => { m.set(k, v); },
    removeItem: (k) => { m.delete(k); },
    clear: () => m.clear(),
    get length() { return m.size; },
    key: (i) => Array.from(m.keys())[i] ?? null,
  };
};

const getStorage = (): Storage => {
  if (typeof window === 'undefined') return createMemoryStorage();
  if (isStorageUsable(window.localStorage)) return window.localStorage;
  if (isStorageUsable(window.sessionStorage)) return window.sessionStorage;
  return createMemoryStorage();
};

// Create client without strict typing to bypass empty Database type
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});